### ISSUE TITLE
invalid byte sequence in US-ASCII

### ISSUE THREAD

**Issue by ghost** [zzamboni/enwrite#17]
It looks like the tool is choking at emoji in the note title:

````
2019-01-30 19:29:10 UTC 2019 Enwrite [INFO]: Found note 'Note from ♻️Cleanup day!'
2019-01-30 19:29:10 UTC 2019 Enwrite [INFO]:    It has the 'markdown' tag, so I will interpret it as markdown
/var/lib/gems/2.3.0/gems/enwrite-0.2.5/lib/output/hugo.rb:154:in `block in output_note': invalid byte sequence in US-ASCII (ArgumentError)
	from /var/lib/gems/2.3.0/gems/enwrite-0.2.5/lib/output/hugo.rb:147:in `chdir'
	from /var/lib/gems/2.3.0/gems/enwrite-0.2.5/lib/output/hugo.rb:147:in `output_note'
	from /var/lib/gems/2.3.0/gems/enwrite-0.2.5/lib/enwrite.rb:284:in `block in run'
	from /var/lib/gems/2.3.0/gems/enwrite-0.2.5/lib/enwrite.rb:279:in `each'
	from /var/lib/gems/2.3.0/gems/enwrite-0.2.5/lib/enwrite.rb:279:in `run'
	from /var/lib/gems/2.3.0/gems/enwrite-0.2.5/bin/enwrite:10:in `<top (required)>'
	from /usr/local/bin/enwrite:22:in `load'
	from /usr/local/bin/enwrite:22:in `<main>'
Exited with code 1
````

**Comment by ghost** [comment]
The above error occurs inside CI docker container and might be related to locale config:
````bash
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
````
